### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by ioscit** [levinhax/Egg-API#2]
egg deprecated [egg-security] `app.config.security.csrf.ignoreJSON` is not safe now, please disable it. node_modules\_egg-core@4.11.0@egg-core\lib\lifecycle.js:93:9
2018-11-16 22:27:21,493 ERROR 6904 [egg-mongoose] mongodb://127.0.0.1/apiExample disconnected
2018-11-16 22:27:21,497 ERROR 6904 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 6904
hostname: DESKTOP-106KQGJ

2018-11-16 22:27:21,503 ERROR 6904 [-/127.0.0.1/-/1ms GET /] nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 6904
hostname: DESKTOP-106KQGJ

2018-11-16 22:27:21,508 ERROR 6904 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_mongodb-core@3.1.7@mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 6904
hostname: DESKTOP-106KQGJ

2018-11-16 22:27:21,511 ERROR 6904 [app_worker] start error, exiting with code:1
[2018-11-16 22:27:21.524] [cfork:master:4972] worker:6904 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
2018-11-16 22:27:21,528 WARN 7056 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2018-11-16 22:27:21.530] [cfork:master:4972] don't fork, because worker:6904 will be kill soon
2018-11-16 22:27:21,533 INFO 4972 [master] app_worker#1:6904 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2018-11-16 22:27:21.538] [cfork:master:4972] worker:6904 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2018-11-16 22:27:21,541 ERROR 4972 nodejs.AppWorkerDiedError: [master] app_worker#1:6904 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_egg-cluster@1.22.1@egg-cluster\lib\master.js:398:21)
    at Master.emit (events.js:182:13)
    at Messenger.sendToMaster (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_egg-cluster@1.22.1@egg-cluster\lib\utils\messenger.js:133:17)
    at Messenger.send (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_egg-cluster@1.22.1@egg-cluster\lib\utils\messenger.js:98:12)
    at EventEmitter.cluster.on (C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_egg-cluster@1.22.1@egg-cluster\lib\master.js:267:22)
    at EventEmitter.emit (events.js:187:15)
    at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
name: "AppWorkerDiedError"
pid: 4972
hostname: DESKTOP-106KQGJ

2018-11-16 22:27:21,543 ERROR 4972 [master] app_worker#1:6904 start fail, exiting with code:1
2018-11-16 22:27:21,545 ERROR 4972 [master] exit with code:1
⚠️  Error: C:\Users\root\Downloads\Egg-API-master\Egg-API-master\node_modules\_egg-bin@4.9.0@egg-bin\lib\start-cluster {"baseDir":"C:\\Users\\root\\Downloads\\Egg-API-master\\Egg-API-master","workers":1,"framework":"C:\\Users\\root\\Downloads\\Egg-API-master\\Egg-API-master\\node_modules\\egg"} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Egg-API@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Egg-API@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\root\AppData\Roaming\npm-cache\_logs\2018-11-16T14_27_21_597Z-debug.log

**Comment by ioscit** [comment]
大佬别用英文回 谢

**Comment by ioscit** [comment]
搞定了 不出错 但是页面是 hello egg

**Comment by ioscit** [comment]
=-=搞好了

**Comment by smilexumu** [comment]
所以是什么原因

**Comment by smilexumu** [comment]
> =-=搞好了

是什么原因呢

**Comment by Lostfishh** [comment]
nothing

**Comment by Lostfishh** [comment]
> > =-=搞好了
> 
> 是什么原因呢

搞定了，

> > =-=搞好了
> 
> 是什么原因呢

搞定了，先把你的mongodb服务跑起来，然后把config.default.js里面的MySQL配置注释掉。

**Comment by oneWalker** [comment]
数据库的问题，把数据库注释了就好了
