### ISSUE TITLE
deleteuser验证失败后中间件errorHandler捕获不到插件egg-validate报的422错误

### ISSUE THREAD

**Issue by dropbug** [levinhax/Egg-API#3]
测试方法：api/v1/deleteuser
参数{"_id":"5c0e0db0f920d60a6d8dae04","userRole":"1","deleteUserId":"u1"}

返回状态码：404
Response Body:{"message":"Not Found"}

------分割线--------
请求数据中，用户角色是1。不满足 controller.user.deleteUser中userRole必须是3的rule.
ctx.validate失败，抛出422错误。
但是外面的errorHandler没有捕获到这个错误。

`userMsg: {"_id":"5c0e0db0f920d60a6d8dae04","userRole":"1","deleteUserId":"u1"}
{ UnprocessableEntityError: Validation Failed
    at Object.throw (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa/lib/context.js:97:11)
    at Object.validate (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/egg-validate/app/extend/context.js:14:17)
    at UserController.deleteUser (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/app/controller/user.js:106:15)
    at Object.callFn (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/Users/leo/VSCodeProjects/极刊登/ji-listing-server/node_modules/koa-compose/index.js:42:32)
    at /Users/leo/VSCodeProjects/极刊登/ji-listing-server/app/middleware/jwt.js:30:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'Validation Failed',
  code: 'invalid_param',
  errors:
   [ { message: 'should be one of 3',
       code: 'invalid',
       field: 'userRole' } ] }`

**Comment by dropbug** [comment]
jwt里捕获之后没有继续抛
